config/routes.rb
Rails.application.routes.draw do

  root "users#index"

  resources :locations, only: [:index, :show] do
    resources :comments, only: [:new, :create, :destroy]
  end

  get '/nearby', to: 'locations#generate_shelters', as: :nearby_shelters

  resources :users, except: [:destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :comments do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :sessions, only: [:create]

  get    '/login',  to: 'sessions#new'

  delete '/logout', to: 'sessions#destroy'

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  validates :body,
  presence: { mesage: "Comment can't be blank" }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize, only: [:create, :new, :destroy]
  before_action :find_commentable
  before_action :check_if_comment_belongs_to_current_user, only: [:destroy]

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new(comment_params) do |u|
      u.author = user_params
      u.user_id = user_identification
    end
    if @comment.save
      redirect_to :back, notice: 'Your comment was successfully posted.'
    else
      redirect_to :back, notice: 'Your comment was not posted.'
    end
  end

  def destroy
    @user = current_user
    @comment = Comment.find(params[:comment_id])
    if @comment.user_id == @user.id
      @comment.comments.destroy_all
      @comment.destroy
      redirect_to :back
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end

  def user_params
    current_user.name
  end

  def user_identification
    current_user.id
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = User.find_by_id(params[:user_id]) if params[:user_id]
    @commentable = Location.find_by_id(params[:location_id]) if params[:location_id]
  end

  def check_if_comment_belongs_to_current_user
    @user = current_user
    @comment = Comment.find(params[:comment_id])
    if @comment[:user_id] == @user.id
      true
    else
      false
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<!-- Displays Comments created from locations/show and users/show view pages -->

<% if current_user %>
  <li class="list-group-item">
    <div class="panel panel-primary panel-default">
      <div class="panel-heading">
      <br/>
        <div class="panel panel-info" style="width: auto; padding: 5px;">
          <p class="comment-body"><%= comment.body %></p>
          <p class="comment-created-at"><%= comment.created_at.in_time_zone('Pacific Time (US & Canada)').strftime("%A %l:%M %P at %B %Y") %></p>
          <p class="comment-author">from <%= comment.author %></p>
          <br/>
          <% if comment.user_id == current_user.id %>
            <div class="div-wrapper">
              <%= link_to "Delete", comment_comment_path(comment.id), method: :delete, class: "del_comment_link bg-success btn btn-link" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <%= form_for [comment, Comment.new] do |c| %>
      <%= c.text_area :body, placeholder: "Add a Reply" %><br/>
      <%= c.submit "Reply"  %>
    <% end %>
    <br/>
    </div>
    <ul class="list-group panel panel-info">
        <%= render partial: 'comments/comment', collection: comment.comments %>
    </ul>
  </li>
<% end %>


<!-- Comments Section for replying -->