config/routes.rb
Rails.application.routes.draw do

  root "users#index"

  resources :locations, only: [:index, :show] do
    resources :comments, only: [:new, :create, :destroy]
  end

  get '/nearby', to: 'locations#generate_shelters', as: :nearby_shelters

  resources :users, except: [:destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :comments do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :sessions, only: [:create]

  get    '/login',  to: 'sessions#new'

  delete '/logout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :locations

  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, presence: true

  validates :username,
  presence: true,
  uniqueness: true

  validates :email,
  presence: true,
  uniqueness: { case_sensitive: false },
  format:
  {
    with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i,
    on: :create
  }

  validates :password,
  presence: true,
  length: 6..20,
  confirmation: true

  validates :current_city,
  presence: true

  validates :current_state,
  format:
  {
    with: %r{\A(?:(A[KLRZ]|C[AOT]|D[CE]|FL|GA|HI|I[ADLN]|K[SY]|LA|M[ADEINOST]|N[CDEHJMVY]|O[HKR]|P[AR]|RI|S[CD]|T[NX]|UT|V[AIT]|W[AIVY]))\z}, message: 'must be formatted as state initials. e.g. CA for California',
    :on => :create
  }

  validates :current_country,
  presence: true,
  format:
  {
    with: %r{\A(?-i:A[DEFGILMNOQRSTUWZ]|B[ABDEFGHIJMNORSTVWYZ]|C[ACDFGHIKLMNORSUVXYZ]|D[EJKMOZ]|E[CEGHRST]|F[IJKMOR]|G[ABDEFHILMNPQRSTUWY]|H[KMNRTU]|I[DELNOQRST]|J[MOP]|K[EGHIMNPRWYZ]|L[ABCIKRSTUVY]|M[ACDGHKLMNOPQRSTUVWXYZ]|N[ACEFGILOPRUZ]|O[M]|P[AEFGHKLMNRSTWY]|QA|R[EOUW]|S[ABCDEGHIJKLMNORTVYZ]|T[CDFGHJKLMNORTVWZ]|U[AGMSYZ]|V[ACEGINU]|W[FS]|Y[ET]|Z[AMW])\z}, message: 'must be formatted as US for United States',
    :on => :create
  }

  validates :bio,
  presence: true

  def self.search(query)
    wildcarded_query = "%#{query}%"
    where(
      "name ILIKE :name OR username ILIKE :username",
      name: wildcarded_query,
      username: wildcarded_query
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:edit, :update, :logout]
  before_action :correct_user, only: [:edit, :update, :logout]

  def index
    @users = User.all
    if params[:search]
      @locations = Location.search(params[:search]).order("created_at DESC").page(params[:page]).per(10)
    else
      @locations = Location.all.order("name").page(params[:page]).per(10)
      flash[:notice] = "No results match search"
    end
    if params[:search]
      @searched_users = User.search(params[:search]).order("created_at DESC").page(params[:page]).per(20)
    else
      @searched_users = User.all.order("name").page(params[:page]).per(20)
      flash[:notice] = "We couldn't find #{params[:search]}."
    end
  end

  def show
    @user = User.find(params[:id])
    @locations = @user.locations
    @suggested_shelter_locations = @locations.order("name").page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up"
      redirect_to root_path
    else
      render 'new'
    end
end

  def update
    if @user.update(user_params)
      redirect_to user_path
      flash[:notice] = "Updated Profile"
    else
      redirect_to edit_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :current_city, :current_state, :current_country, :password, :password_confirmation, :bio)
  end

  def location_params
    params.require(:location).permit(:address, :latitude, :longitude, :user_id, :gmaps)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- Edit Profile Page def needs some slight work -->
<div id="add_new_user">
  <h1 style="margin: 0px auto;">
    <u>Edit Profile</u>
  </h1>
  <br/>
  <%= form_for @user do |c| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= c.label :name %>
      <%= c.text_field :name, :class => "name_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :username %>
      <%= c.text_field :username, :class => "username_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :bio %>
      <%= c.text_area :bio, class: "bio_input_user_edit" %>
    </div>
    <div class="field">
      <%= c.label :current_city %>
      <%= c.text_field :current_city, :class => "current_city_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :current_state %>
      <%= c.text_field :current_state, :class => "current_state_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :current_country %>
      <%= c.text_field :current_country, :class => "current_country_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :email %>
      <%= c.text_field :email, :class => "email_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :password %>
      <%= c.password_field :password, :class => "password_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :password_confirmation %>
      <%= c.password_field :password_confirmation, :class => "password_confirmation_input_new_user" %>
    </div>
    <br/>
    <div class="actions">
      <%= c.submit %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<!-- Location Search Bar -->
<section class="form-group align-right" style="display: block;">
  <%= bootstrap_form_tag location: locations_path, method: :get do |p| %>
    <br/>
    <br/>
    <br/>
    <br/>
    <%= p.text_field :search, placeholder: "search shelters", hide_label: true, value: params[:search], autofocus: true  %>
  <% end %>
  <!-- Link takes user/guest to /locations/index page so all locations -->
  <%= link_to "Clear", users_path, class: "btn btn-primary" %>
</section>

<div id="locations_container">
<!-- If something was searched when pressing enter in the search input form brings it up -->
<!-- If user/guest pressed enter with no input in the search input form brings
     up all locations our db currently has from all users -->
     <!-- This and the maps should be available for both guests and users -->
  <% if params[:search] %>
    <h1 style="color: black">Search Results for <%= "#{params[:search]}" %></h1>
      <table class="table table-hover"cellpadding="10">
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Latitude</th>
        <th>Longitude</th>
      </tr>

      <% for location in @locations %>
        <tr>
          <td><%= link_to "#{location.name}", location, class: 'show_loc_link' %></td>
          <td><%= link_to "#{location.address}", location, class: 'show_loc_link' %></td>
          <td><%= location.latitude %></td>
          <td><%= location.longitude %></td>
        </tr>
      <% end %>
    </table>
    <!-- check out Kaminari gem github for styling docs https://github.com/amatsuda/kaminari-->
    <%= paginate @locations %>
  <% else %>
      <!-- Include normal html landing page options for both logged in users and guests of the site  -->
  <legend>Got a place in mind? Look it up!</legend>
  <div class="map-container">
    <input id="origin-input" class="controls" type="text"
        placeholder="Enter an origin location">

    <input id="destination-input" class="controls" type="text"
        placeholder="Enter a destination location">

    <div id="mode-selector" class="controls">
      <input type="radio" name="type" id="changemode-walking" checked="checked">
      <label for="changemode-walking">Walking</label>

      <input type="radio" name="type" id="changemode-transit">
      <label for="changemode-transit">Transit</label>

      <input type="radio" name="type" id="changemode-driving">
      <label for="changemode-driving">Driving</label>
    </div>

    <div id="map"></div>
  </div>
  <!-- Include normal html landing page options for both logged in users and guests of the site  -->
    <% end %>
</div>

app/views/users/new.html.erb
<!-- Sign Up Form Page needs some slight work -->
<div id="add_new_user">
  <h1 style="margin: 0px auto;">
    <u>Sign Up</u>
  </h1>
  <br/>
  <%= form_for @user do |c| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= c.label :name %>
      <%= c.text_field :name, :class => "name_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :username %>
      <%= c.text_field :username, :class => "username_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :email %>
      <%= c.text_field :email, :class => "email_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :password %>
      <%= c.password_field :password, :class => "password_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :password_confirmation %>
      <%= c.password_field :password_confirmation, :class => "password_confirmation_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :current_city %>
      <%= c.text_field :current_city, :class => "current_city_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :current_state %>
      <%= c.text_field :current_state, :class => "current_state_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :current_country %>
      <%= c.text_field :current_country, :class => "current_country_input_new_user" %>
    </div>
    <div class="field">
      <%= c.label :bio %>
      <%= c.text_area :bio, class: "bio_input_user_edit" %>
    </div>
    <br/>
    <div class="actions">
      <%= c.submit %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<!-- User Bio Section -->
<div>
  <h1><%= @user.name %></h1>
  <br/>
  <div style="background-color: lightblue" class="jumbotron">
    <p><%= @user.bio %></p>
<!-- Couldn't get the help users features delivered in time -->
<!-- <p><a class="btn btn-success btn-lg" href="#" role="button">Help <%= @user.name %></a></p> -->
  </div>
</div>

<!-- List of Locations Genereated Through nearby_shelters Method for each current_city for the current_user -->
<h1>Suggested Shelters</h1>
<table class="table table-hover" cellpadding="10">
  <tr>
    <th>Name</th>
    <th>Address</th>
  </tr>
  <% for location in @suggested_shelter_locations %>
    <tr>
      <td><%= link_to "#{location.name}", location, class: 'show_loc_link' %></td>
      <td><%= link_to "#{location.address}", location_path(location.id), class: 'show_loc_link' %></td>
    </tr>
  <% end %>
</table>
<!-- check out Kaminari gem github for styling docs https://github.com/amatsuda/kaminari-->
<%= paginate @suggested_shelter_locations %>

<% if current_user %>
  <!-- Comments Section -->
  <% @user = User.find(params[:id]) %>
  <h1>Leave <%= @user.name %> a comment!</h1>
  <div class="panel panel-primary panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Comments</h3>
    </div>
    <div class="panel panel-body">
      <div>
        <%= form_for [@user, Comment.new] do |c| %>
          <%= c.text_area :body, placeholder: "Add a comment", autofocus: true %>
          <br/>
          <%= c.submit "Comment" %>
        <% end %>
      </div>

      <ul class="list-group">
        <%= render(partial: 'comments/comment', collection: @user.comments) %>
      </ul>
    </div>
  </div>
<% end %>